// Course catalogue for the SCORE QC site. Details come from the SCORE QC brochure and scoreqc.com course pages.
// `dur` / `elig` left null where the source gives none: the page then says "Ask a counsellor".
module.exports.CATEGORIES = [
  { id: 'qaqc', name: 'QA/QC Courses', short: 'QA/QC', blurb: 'Inspection, testing and quality control for mechanical, civil and electrical projects.' },
  { id: 'mep', name: 'MEP Courses', short: 'MEP', blurb: 'Mechanical, electrical and plumbing design for buildings and industrial plants.' },
  { id: 'software', name: 'Software Courses', short: 'Software', blurb: 'Industry-standard design, drafting, planning and analysis software.' },
  { id: 'intl', name: 'International Certification Courses', short: 'International', blurb: 'Exam-focused preparation for TWI, AWS, API, AMPP (NACE) and ISO credentials.' },
  { id: 'diploma', name: 'Professional Diploma Courses', short: 'Diplomas', blurb: 'Longer career programmes that combine theory, software and hands-on training.' },
  { id: 'short', name: 'Short Term Courses', short: 'Short Term', blurb: 'Focused programmes to add a practical skill quickly.' }
];

const STED = 'STED Council, Govt. of India';
const ASNT = 'ASNT (American Society for Nondestructive Testing)';

module.exports.COURSES = [
  // ---------------- QA/QC ----------------
  { slug: 'asnt-level-2-ndt', cat: 'qaqc', title: 'ASNT Level II – NDT', tag: 'Non-Destructive Testing',
    short: 'Theory and hands-on practice in the most widely used NDT methods, to ASNT Level I & II.',
    overview: 'NDT is the process of inspecting, testing or evaluating a material, component or assembly for discontinuities without destroying its serviceability. The programme gives comprehensive theoretical and practical training in the most widely used NDT methods, delivered by faculty with long professional and teaching backgrounds.',
    dur: '20 days', elig: '10th / Plus Two / ITI / Diploma / Degree', cert: ASNT,
    learn: ['Liquid Penetrant Testing (PT)', 'Magnetic Particle Testing (MT)', 'Ultrasonic Testing (UT)', 'Radiographic Testing (RT)', 'Radiographic Test Film Interpretation (RTFI)', 'Visual Testing (VT)'],
    prompt: 'an NDT technician in a white hard hat and safety glasses performing fluorescent magnetic particle testing on a steel weld under a UV lamp, bright green indications glowing on the dark steel, dim inspection bay' },
  { slug: 'qaqc-mechanical', cat: 'qaqc', title: 'QA/QC – Mechanical', tag: 'Quality Assurance & Control',
    short: 'NDT, welding and painting inspection, codes, metallurgy and piping in one programme.',
    overview: 'Quality Assurance is process-oriented and focuses on preventing defects; Quality Control is product-oriented and focuses on finding them. This programme builds both skill sets for mechanical projects, combining ASNT Level I & II NDT with welding and painting inspection, codes and standards, metallurgy and piping engineering.',
    dur: '45 days', elig: 'Diploma / Degree in Mechanical Engineering', cert: ASNT + ' · ' + STED,
    learn: ['ASNT Level I & II NDT (PT, MT, UT, RT, RTFI, VT)', 'Welding inspection', 'Painting inspection', 'Codes & standards', 'Metallurgy', 'Piping components, fittings & process piping codes', 'Isometric drawings and P&ID', 'Pipe fabrication'],
    note: 'Also available as a QA/QC–MEP combo (60 days) and QA/QC–MEP combo with software (90 days).',
    prompt: 'a South Asian QA/QC engineer in a white hard hat and hi-vis vest inspecting a nozzle weld on a large pressure vessel in a fabrication yard, holding an inspection checklist on a clipboard' },
  { slug: 'qaqc-mechanical-advanced', cat: 'qaqc', title: 'QA/QC – Mechanical (Advanced)', tag: 'Quality Assurance & Control',
    short: 'Takes Mechanical QA/QC further into codes, procedures and inspection planning.',
    overview: 'The advanced programme builds on Mechanical QA/QC for candidates who want to work at engineer level. It goes deeper into applying international codes, qualifying welding procedures, planning inspections and preparing the quality documentation that clients and third-party inspectors expect.',
    dur: null, elig: 'Diploma / Degree in Mechanical Engineering', cert: ASNT + ' · ' + STED,
    learn: ['Advanced NDT interpretation and reporting', 'Applying ASME and API codes on the job', 'Welding procedure and welder qualification', 'Inspection & Test Plans (ITPs)', 'Quality documentation and handover dossiers', 'Coordinating with clients and third-party inspectors'],
    prompt: 'a senior South Asian QA/QC engineer and a junior colleague examining a radiographic film on an illuminated film viewer in a tidy inspection office, weld samples on the desk' },
  { slug: 'document-controller', cat: 'qaqc', title: 'Document Controller (WPS/PQR, Section IX)', tag: 'Welding Documentation',
    short: 'Prepare and control WPS, PQR and welder qualification records to ASME Section IX.',
    overview: 'Every welded job depends on correct paperwork. This course trains you to prepare, review and control welding procedure specifications, procedure qualification records and welder qualification records to ASME Section IX, and to keep project quality records audit-ready.',
    dur: '20 days', elig: 'Plus Two or above', cert: STED,
    learn: ['WPS preparation', 'PQR preparation', 'WQT / WPQ – welder qualification', 'ASME Section IX essentials', 'NDT and inspection report formats', 'Document control and records management'],
    prompt: 'a South Asian document controller at a clean office desk organising welding procedure binders and files, welded test coupons and a laptop beside her, soft daylight' },
  { slug: 'piping-engineering', cat: 'qaqc', title: 'Piping Engineering', tag: 'Process Piping',
    short: 'Pipes, fittings, codes, layouts and P&IDs – with engineer, foreman and supervisor tracks.',
    overview: 'Designed to give aspirants a working knowledge of piping and process piping, pipeline construction, drawings and P&IDs as per codes such as ASME B31.3 and B31.4. Candidates choose between Piping Engineer, Piping Foreman and Piping Supervisor tracks according to their eligibility.',
    dur: '20 days', elig: 'Engineer: Diploma / Degree · Foreman & Supervisor: Plus Two or above', cert: STED,
    learn: ['Pipes, pipe fittings, codes & standards', 'Plot and read piping and equipment layouts', 'P&ID reading', 'Inspection and quality checks of piping systems', 'Pipe fabrication, erection and supports', 'Document control for piping'],
    prompt: 'a South Asian piping engineer in a white hard hat holding an isometric drawing beside a large process piping rack with flanges and valves at a refinery' },
  { slug: 'ndt-civil', cat: 'qaqc', title: 'NDT – Civil', tag: 'Civil NDT',
    short: 'Non-destructive testing of concrete and structures, in theory and in the field.',
    overview: 'A detailed theoretical and practical course on applying NDT techniques to civil structures, so you can assess concrete quality and structural condition without damaging the structure.',
    dur: '10 days', elig: 'ITI / Diploma / Degree', cert: STED + ' · ' + ASNT,
    learn: ['Ultrasonic Pulse Velocity (UPV) testing', 'Rebound hammer testing', 'Radiography of concrete', 'Rebar location and cover measurement', 'Interpreting and reporting results'],
    prompt: 'a South Asian civil engineer in a white hard hat testing a concrete column with a rebound hammer at a building construction site, grid marked on the concrete' },
  { slug: 'qaqc-civil', cat: 'qaqc', title: 'QA/QC – Civil', tag: 'Civil Quality Control',
    short: 'Roles of the civil QA/QC engineer, materials testing and field NDT.',
    overview: 'Covers the testing – destructive and non-destructive – and inspection of materials and works in civil construction, so that they comply with quality and safety laws and industry standards.',
    dur: '20 days', elig: 'ITI / Diploma / Degree', cert: STED + ' · ' + ASNT,
    learn: ['Roles and responsibilities of a QA/QC engineer', 'Testing of construction materials', 'Visual inspection', 'Rebound hammer and Ultrasonic Pulse Velocity tests', 'Windsor probe and pull-out tests', 'Quality records and reporting'],
    prompt: 'a South Asian civil QA/QC engineer supervising a concrete slump test at a construction site, concrete cube moulds on the ground, crane in the background' },
  { slug: 'quantity-surveying', cat: 'qaqc', title: 'Quantity Surveying – Civil', tag: 'Cost & Estimation',
    short: 'Estimate and manage construction costs with BOQs and rate analysis.',
    overview: 'Quantity surveying deals with estimating and managing the costs of construction projects. You get hands-on training in preparing bills of quantities for buildings, highways, culverts and bridges, and in rate analysis.',
    dur: '20 days', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Reading construction drawings for take-off', 'Bill of Quantities (BOQ) preparation', 'BOQs for buildings, highways, culverts and bridges', 'Rate analysis', 'Estimation and cost control basics'],
    prompt: 'a South Asian quantity surveyor measuring construction drawings with a scale ruler, laptop and calculator on the desk, a building site visible through the office window' },
  { slug: 'qaqc-electrical', cat: 'qaqc', title: 'QA/QC – Electrical', tag: 'Electrical Quality Control',
    short: 'Condition monitoring and quality assurance for electrical installations.',
    overview: 'Intended for upskilling personnel in construction electrical procedures and the diagnostic techniques used to assure quality in production and installation activities.',
    dur: '45 days', elig: null, cert: STED,
    learn: ['Vibration analysis', 'Ultrasound analysis', 'Motor signature analysis', 'Electrical signature analysis', 'Thermographic testing', 'Process improvement in oil & gas'],
    prompt: 'a South Asian electrical technician in a hard hat inspecting an open electrical distribution panel with a handheld thermal imaging camera, the camera screen showing a colourful heat map' },
  { slug: 'qaqc-e-and-i', cat: 'qaqc', title: 'QA/QC – E & I', tag: 'Electrical & Instrumentation',
    short: 'Quality control for electrical and instrumentation works in process plants.',
    overview: 'Electrical & Instrumentation (E&I) QA/QC covers the inspection and testing of cables, panels and field instruments on industrial projects, and the checks that prove a system is ready to hand over.',
    dur: null, elig: null, cert: STED,
    learn: ['Inspection of cabling, trays and terminations', 'Instrument calibration checks', 'Loop checking', 'Inspection & Test Plans for E&I works', 'QA documentation and punch lists'],
    prompt: 'a South Asian instrumentation technician calibrating a pressure transmitter with a handheld process calibrator in an industrial plant, instrument tubing and cable trays around' },
  { slug: 'testing-commissioning-electrical', cat: 'qaqc', title: 'Testing & Commissioning – Electrical', tag: 'Electrical T&C',
    short: 'Safety, tools and pre- and post-commissioning of electrical equipment.',
    overview: 'Covers industrial electrical safety, tool handling, and the pre- and post-commissioning of generators, motors, transformers and bus bars, along with procedure preparation and documentation.',
    dur: '30 days', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Basics of industrial electrical safety', 'Tools and handling', 'Pre- & post-commissioning of generators, motors and transformers', 'FAT & SAT procedures', 'Preparation of ITPs'],
    prompt: 'a South Asian electrical engineer in a hard hat testing medium-voltage switchgear with an insulation resistance tester in a clean electrical substation room' },

  // ---------------- MEP ----------------
  { slug: 'mep-designing-drafting', cat: 'mep', title: 'MEP Designing & Drafting', tag: 'Building Services',
    short: 'HVAC, electrical, fire fighting and plumbing design – with or without software.',
    overview: 'Mechanical, electrical and plumbing services are a significant part of every construction project and critical to design, decision making, documentation, performance and cost. The course is offered with and without software.',
    dur: '30 days · 60 days with software', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED + ' · ' + ASNT,
    learn: ['HVAC', 'Electrical', 'Fire fighting', 'Plumbing', 'With software: AutoCAD, HAP and McQuay'],
    note: 'Also offered as MEP–QA/QC combo (60 days) and with software (90 days).',
    prompt: 'a South Asian MEP engineer in a white hard hat looking up at coordinated ductwork, pipes and cable trays in the ceiling of a commercial building under construction, holding a tablet' },
  { slug: 'hvac', cat: 'mep', title: 'HVAC', tag: 'Heating, Ventilation & Air Conditioning',
    short: 'Heat loads, psychrometrics and duct design for comfortable, efficient buildings.',
    overview: 'HVAC is a major sub-discipline of mechanical engineering that deals with indoor air quality and human comfort in buildings. The course is offered with and without software.',
    dur: '20 days · 30 days with software', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Heat transfer methods', 'Heat load calculations (HAP)', 'Psychrometric charts', 'Ventilation', 'Duct design and pipe sizing (McQuay)', 'AutoCAD HVAC drawings'],
    prompt: 'a South Asian HVAC engineer inspecting a large air handling unit and insulated ductwork in a rooftop plant area, open access panel, clear sky' },
  { slug: 'revit-mep', cat: 'mep', also: ['software'], title: 'Revit MEP', tag: 'BIM for MEP',
    short: 'Model, coordinate and document building services in Autodesk Revit.',
    overview: 'Revit MEP is a building information modelling solution with the tools MEP engineers need: integrated mechanical design and analysis, electrical views, plumbing fixtures and more. The training helps you work faster and streamline design and documentation workflows.',
    dur: '60 days', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Revit interface and project setup', 'HVAC ducts and equipment modelling', 'Piping and plumbing systems', 'Electrical systems and lighting', 'Clash coordination', 'Sheets, schedules and documentation'],
    prompt: 'a South Asian BIM designer at dual monitors showing a colourful 3D model of building services with blue ducts and red and green pipes, modern design office' },
  { slug: 'electrical-mep', cat: 'mep', title: 'Electrical MEP', tag: 'Electrical Building Services',
    short: 'Power distribution, SLDs, sizing and routing for buildings and plants.',
    overview: 'A detailed study of electrical building systems – power supply and distribution, control systems, standards, estimation and forecasting, sizing of components and single line diagrams – using both manual and software calculations.',
    dur: '30 days', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Electrical safety', 'Tools and handling', 'Conductor and wire routing', 'Basic single line diagrams (SLD)', 'Switchgear', 'Load estimation and sizing'],
    prompt: 'a South Asian electrical engineer checking cable routing in a cable tray beside a main distribution board in a commercial building plant room' },

  // ---------------- SOFTWARE ----------------
  { slug: 'autocad-2d-3d', cat: 'software', title: 'AutoCAD 2D & 3D', tag: 'Drafting & Modelling',
    short: 'Produce accurate 2D drawings and 3D models for engineering projects.',
    overview: 'AutoCAD remains the standard drafting tool across engineering disciplines. This course takes you from 2D drafting to 3D modelling, with the drawing practices used on real projects.',
    dur: '20 days', elig: 'Plus Two or above', cert: STED,
    learn: ['2D drafting and editing', 'Layers, blocks and annotation', 'Dimensioning to standards', '3D solid and surface modelling', 'Layouts, plotting and printing'],
    prompt: 'a South Asian drafter at a workstation with a detailed 2D CAD floor plan on a large monitor, rolled blueprints on the desk, bright office' },
  { slug: 'primavera', cat: 'software', title: 'Primavera', tag: 'Project Planning & Management',
    short: 'Plan, schedule and track projects in Primavera P6.',
    overview: 'Primavera is the planning tool of choice for large construction and oil & gas projects. Learn to build schedules, load resources, track progress and report on real project data.',
    dur: '20 days', elig: 'Plus Two or above', cert: STED,
    learn: ['Project and WBS setup', 'Activities, relationships and scheduling', 'Resource and cost loading', 'Baselines and progress tracking', 'Reports and layouts'],
    prompt: 'a South Asian project planner at a large monitor showing a colourful Gantt-style schedule with bars, construction site photos pinned on the wall behind, modern office' },
  { slug: 'electrical-designing', cat: 'software', title: 'Electrical Designing', tag: 'Electrical Design Software',
    short: 'Load estimation, sizing and protection – the core of electrical design.',
    overview: 'Learn the calculations behind electrical design: estimating and forecasting load, and sizing transformers, cables, batteries, UPS and generators, with software to speed up and check the work. It forms the first level of the Professional Diploma in Electrical Designing.',
    dur: '30 days', elig: 'Diploma / Degree', cert: STED,
    learn: ['Load estimation and forecasting', 'Sizing of transformers', 'Selection and sizing of cables', 'Sizing of batteries, inverters and UPS', 'Selection of circuit breakers', 'Sizing of generators'],
    prompt: 'a South Asian electrical design engineer at a monitor showing a clean electrical single line diagram schematic, printed schematics and a calculator on the desk' },
  { slug: 'dialux', cat: 'software', title: 'DIALux – Electrical', tag: 'Lighting Design',
    short: 'Design, calculate and visualise lighting for interiors, streets and exteriors.',
    overview: 'DIALux is professional lighting design software that helps you design, calculate and visualise light – from single rooms and whole floors to buildings and outdoor scenes.',
    dur: '7 days', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Indoor lighting design', 'Street-side lighting', 'Exterior lighting', 'Lux calculations and reports'],
    prompt: 'a South Asian lighting designer at a monitor showing a photorealistic 3D rendered room with lighting simulation, LED luminaire samples on the desk, dim modern studio' },
  { slug: 'revit-architecture', cat: 'software', title: 'Revit Architecture', tag: 'BIM for Architecture',
    short: 'Model buildings and produce coordinated drawings in Autodesk Revit.',
    overview: 'Revit Architecture lets you design a building once as an intelligent 3D model and generate plans, sections, elevations and schedules from it. The course covers the full workflow from concept to documentation.',
    dur: null, elig: null, cert: STED,
    learn: ['Walls, floors, roofs and stairs', 'Families and components', 'Views, sections and elevations', 'Schedules and quantities', 'Sheets and documentation', 'Rendering and walkthroughs'],
    prompt: 'a South Asian architect at a monitor showing a 3D model of a modern glass building, a white physical scale model of the building on the desk' },
  { slug: '3ds-max', cat: 'software', title: '3ds Max', tag: '3D Visualisation',
    short: 'Create photorealistic 3D renders and walkthroughs.',
    overview: '3ds Max is widely used to turn designs into convincing visuals. Learn modelling, materials, lighting and rendering to present architectural and interior projects.',
    dur: null, elig: null, cert: STED,
    learn: ['3D modelling techniques', 'Materials and texturing', 'Lighting and cameras', 'Photorealistic rendering', 'Animation and walkthroughs'],
    prompt: 'a South Asian 3D visualisation artist at a large monitor showing a photorealistic rendered luxury interior, a graphics tablet and stylus on the desk, moody studio lighting' },
  { slug: 'staad-pro', cat: 'software', title: 'STAAD.Pro', tag: 'Structural Analysis',
    short: 'Model, analyse and design structures in STAAD.Pro.',
    overview: 'STAAD.Pro is used to analyse and design steel and concrete structures. Learn to model structures, apply loads and combinations, run analysis and design members to code.',
    dur: null, elig: null, cert: STED,
    learn: ['Structural modelling', 'Loads and load combinations', 'Static analysis', 'Steel design', 'Concrete design', 'Output and reports'],
    prompt: 'a South Asian structural engineer at a monitor showing a 3D steel frame building model with colourful stress contour diagrams, engineering drawings on the desk' },

  // ---------------- INTERNATIONAL ----------------
  { slug: 'cswip-3-1', cat: 'intl', title: 'CSWIP 3.1 – Welding Inspector', tag: 'TWI, United Kingdom',
    short: 'The world’s most recognised welding inspector credential – examined on our campus.',
    overview: 'CSWIP (Certification Scheme for Welding Inspection & Personnel) is run by TWI, The Welding Institute, UK. CSWIP 3.1 starts your career as a certified welding inspector. SCORE QC is the only CSWIP course provider in Trivandrum, offering exam-oriented theory and practical sessions with a pass rate above 95%.',
    dur: null, elig: 'Minimum 3 years’ experience in NDT / welding-related operations', cert: 'TWI – The Welding Institute, United Kingdom',
    learn: ['Welding processes and terminology', 'Welding imperfections and defectology', 'Codes and standards', 'Visual inspection of welds', 'Destructive and non-destructive testing awareness', 'Practical plate and pipe assessment'],
    link: { href: '../#cswip-page', label: 'Read the full CSWIP guide' },
    prompt: 'a South Asian certified welding inspector in a white hard hat using a stainless steel weld gauge on a large butt weld of a steel plate in a bright fabrication shop' },
  { slug: 'cswip-3-2', cat: 'intl', title: 'CSWIP 3.2 – Senior Welding Inspector', tag: 'TWI, United Kingdom',
    short: 'Step up from CSWIP 3.1 to senior welding inspector.',
    overview: 'With experience, CSWIP 3.1 holders can progress to CSWIP 3.2, which qualifies them to work as Senior Welding Inspectors across industrial sectors, including radiographic interpretation and supervising other inspectors.',
    dur: null, elig: 'Minimum 5 years’ experience in NDT / welding-related operations', cert: 'TWI – The Welding Institute, United Kingdom',
    learn: ['Advanced welding metallurgy', 'Radiographic interpretation', 'Welding procedures and qualifications', 'Quality assurance and inspection planning', 'Supervising welding inspection teams'],
    prompt: 'a senior South Asian welding inspector reviewing a weld radiograph against a light panel while mentoring a junior inspector, pipeline spools in the background' },
  { slug: 'aws-cwi', cat: 'intl', title: 'AWS – Certified Welding Inspector (CWI)', tag: 'American Welding Society',
    short: 'Exam preparation for the American Welding Society CWI.',
    overview: 'The American Welding Society is a leading authority on welding inspection. The scheme covers welding metallurgy, welding symbols and geometry, welding imperfections, welding and cutting processes, visual inspection and applying codes. SCORE QC is the only institute providing the AWS course in Trivandrum.',
    dur: null, elig: 'Minimum 3 years’ experience in NDT / welding-related operations', cert: 'American Welding Society (AWS)',
    learn: ['Welding metallurgy', 'Welding symbols and geometry', 'Welding imperfections', 'Welding and cutting processes', 'Visual inspection', 'Applying codes'],
    prompt: 'a South Asian welding inspector with a flashlight and magnifier visually inspecting a fillet weld on a structural steel beam at a construction site' },
  { slug: 'bgas-grade-2', cat: 'intl', title: 'BGAS Grade 2 – Painting Inspector', tag: 'TWI · BGAS-CSWIP',
    short: 'Start a career in industrial painting and coating inspection.',
    overview: 'BGAS, provided by TWI, suits candidates building a career in industrial painting or coating inspection. It covers most paint systems used in industry and the coating systems used to prevent corrosion. SCORE QC is the only institute providing BGAS in Trivandrum.',
    dur: null, elig: 'Six months or more experience in painting / coating', cert: 'TWI – The Welding Institute, United Kingdom',
    learn: ['Corrosion and surface preparation', 'Paint systems and coating types', 'Inspection instruments', 'Dry and wet film thickness measurement', 'Coating defects and reporting'],
    prompt: 'a South Asian coating inspector measuring dry film thickness with a digital DFT gauge on a freshly painted steel structure in a paint shop' },
  { slug: 'bgas-grade-1', cat: 'intl', title: 'BGAS Grade 1 – Senior Painting Inspector', tag: 'TWI · Offshore',
    short: 'Senior painting inspector certification, including offshore work.',
    overview: 'BGAS Grade 1 is the senior painting inspector level, suited to inspectors responsible for coating work on offshore and major onshore assets.',
    dur: null, elig: 'Six months or more experience in painting / coating', cert: 'TWI – The Welding Institute, United Kingdom',
    learn: ['Advanced coating specifications', 'Offshore coating systems', 'Inspection planning and supervision', 'Failure investigation', 'Reporting and client interface'],
    prompt: 'a South Asian coating inspector on an offshore platform deck checking a freshly painted steel structure with an inspection gauge, sea and sky in the background' },
  { slug: 'aws-to-cswip-bridging', cat: 'intl', title: 'AWS to CSWIP Bridging', tag: 'TWI · AWS holders',
    short: 'A fast route to CSWIP 3.1 for current AWS CWIs.',
    overview: 'For current AWS Certified Welding Inspectors who want to add the CSWIP 3.1 credential, the bridging course focuses on the differences between the two schemes and prepares you for the CSWIP examination.',
    dur: null, elig: 'Current AWS Certified Welding Inspector', cert: 'TWI – The Welding Institute, United Kingdom',
    learn: ['CSWIP scheme requirements', 'European and international standards', 'Practical weld assessment', 'Examination technique'],
    prompt: 'a South Asian welding inspector studying technical code books with weld sample coupons and a weld gauge on a classroom desk, focused, warm light' },
  { slug: 'api-certifications', cat: 'intl', title: 'API 510, 570, 653, 571, 577, 580, 936, 1169', tag: 'American Petroleum Institute',
    short: 'Preparation and exam registration support for API individual certifications.',
    overview: 'The American Petroleum Institute is the largest US trade association for the oil and natural gas industry. API-certified inspectors are recognised worldwide as professionals who know the relevant inspection codes and work to the latest industry practice. We prepare candidates and help them register for the international examinations.',
    dur: null, elig: 'As per API experience requirements for each certification', cert: 'American Petroleum Institute (API)',
    learn: ['API 510 – Pressure Vessel Inspector', 'API 570 – Piping Inspector', 'API 653 – Aboveground Storage Tank Inspector', 'API 571 – Corrosion & Materials', 'API 577 – Welding Inspection & Metallurgy', 'API 580 – Risk Based Inspection', 'API 936 – Refractory Personnel', 'API 1169 – Pipeline Construction Inspector'],
    prompt: 'a South Asian inspector in a hard hat measuring wall thickness with an ultrasonic thickness gauge on a large refinery pressure vessel, storage tanks behind' },
  { slug: 'nace-cip-level-1', cat: 'intl', title: 'NACE CIP Level 1', tag: 'Coating Inspector Program · AMPP',
    short: 'Entry level of the world’s most recognised coating inspector programme.',
    overview: 'The NACE Coating Inspector Program (now under AMPP) sets the standard for inspection in the protective coatings industry. SCORE QC is the only institute in Trivandrum providing preparatory courses for CIP Level 1 and 2.',
    dur: null, elig: 'No prerequisites', cert: 'AMPP (formerly NACE International)',
    learn: ['Corrosion basics', 'Surface preparation', 'Coating types and application', 'Inspection instruments', 'Inspection procedures and reporting'],
    prompt: 'a South Asian coating inspector checking wet film thickness with a wet film comb on a freshly sprayed steel plate in an industrial paint booth' },
  { slug: 'nace-cip-level-2', cat: 'intl', title: 'NACE CIP Level 2', tag: 'Coating Inspector Program · AMPP',
    short: 'Advanced coating inspection, including specialised techniques.',
    overview: 'CIP Level 2 builds on Level 1 with advanced inspection techniques, specialised application methods and coating surveys.',
    dur: null, elig: 'Minimum 2 years’ experience in coating-related operations', cert: 'AMPP (formerly NACE International)',
    learn: ['Advanced inspection techniques', 'Holiday detection', 'Cathodic protection awareness', 'Specialised coatings and linings', 'Coating surveys and failure analysis'],
    prompt: 'a South Asian coating inspector running a holiday detector along a coated steel pipeline in the field, pipe supports and sky behind' },
  { slug: 'iso-lead-auditor', cat: 'intl', title: 'ISO Lead Auditor', tag: 'Management Systems',
    short: 'Plan and lead audits of ISO management systems.',
    overview: 'Lead auditor training for the major ISO management system standards, covering how to plan, conduct, report and follow up on audits.',
    dur: '7 days', elig: 'Plus Two or above', cert: 'IRCA & CQI',
    learn: ['ISO 9001 – Quality', 'ISO 14001 – Environment', 'ISO 18001 – Occupational health & safety', 'ISO 22000 – Food safety', 'ISO 27001 – Information security', 'ISO 50001 – Energy', 'ISO/TS 16949 – Automotive quality'],
    prompt: 'a South Asian auditor with a clipboard interviewing a plant manager in a clean, organised manufacturing facility, both in safety glasses' },

  // ---------------- DIPLOMAS ----------------
  { slug: 'diploma-oil-gas-technology', cat: 'diploma', title: 'Oil & Gas Technology', tag: 'Professional Diploma',
    short: 'Facilities, processes, quality and inspection across the oil & gas sector.',
    overview: 'A comprehensive course covering the major facilities and processes, quality and inspection, and utility systems in the oil & gas field. You finish well versed in pipeline designs, drawings, codes and standards, and aware of the techniques and machinery used on rigs and in refineries.',
    dur: '6 months / 3 months', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Upstream, midstream and downstream facilities', 'Process and utility systems', 'Pipeline design and drawings', 'Codes and standards', 'Quality and inspection', 'Rig and refinery equipment'],
    prompt: 'South Asian engineers in hard hats walking past refinery process units and distillation columns at dusk, lights coming on' },
  { slug: 'diploma-electrical-designing', cat: 'diploma', title: 'Electrical Designing (ETAP)', tag: 'Professional Diploma',
    short: 'Three levels – load flow, short circuit and ETAP power system analysis.',
    overview: 'A full-spectrum engineering course in the analysis, simulation, monitoring, control and optimisation of electrical power systems, finishing with ETAP, the software the world follows as standard.',
    dur: '3 levels × 30 days', elig: 'Diploma / Degree', cert: STED,
    learn: ['Level 1 – Load flow: load estimation, transformer, cable, UPS and generator sizing', 'Level 2 – Short circuit: line and ground faults, symmetrical & asymmetrical faults', 'Arc flash analysis and protection zones', 'Level 3 – ETAP: load flow and short circuit studies', 'Motor acceleration and transient stability', 'Harmonic analysis'],
    prompt: 'a South Asian electrical engineer with a tablet in a high-voltage outdoor substation with large transformers and busbars at golden hour' },
  { slug: 'diploma-industrial-maintenance', cat: 'diploma', title: 'Industrial Maintenance Engineering (IME)', tag: 'Professional Diploma',
    short: 'A hands-on programme for manufacturing and production maintenance.',
    overview: 'A hands-on course that develops quality skills for the manufacturing and production industry, covering welding engineering, industrial engineering, safety, automobile technology, HVAC and refrigeration.',
    dur: 'One year', elig: 'SSLC / Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['Welding engineering', 'Industrial engineering', 'Industrial safety', 'Automobile technology', 'HVAC and refrigeration', 'Preventive and predictive maintenance'],
    prompt: 'a South Asian maintenance technician aligning a motor and pump coupling with a laser shaft alignment tool in a clean industrial pump house' },
  { slug: 'diploma-construction-management', cat: 'diploma', title: 'Construction Management', tag: 'Professional Diploma',
    short: 'MEP design, Revit MEP, AutoCAD and Primavera in one package.',
    overview: 'An all-in-one package comprising MEP designing & drafting, Revit MEP, AutoCAD and Primavera. The MEP syllabus covers HVAC, heat load calculations, plumbing, electrical and fire fighting, with on-site job training at a reputed company.',
    dur: '6 months / 3 months', elig: 'Plus Two / ITI / Diploma / Degree', cert: STED,
    learn: ['MEP designing & drafting', 'Revit MEP', 'AutoCAD', 'Primavera planning', 'HVAC, plumbing, electrical and fire fighting', 'On-site job training'],
    prompt: 'a South Asian construction manager in a white hard hat with a tablet briefing two site engineers on a high-rise construction site, tower crane above' },
  { slug: 'diploma-welding-inspection', cat: 'diploma', title: 'Welding Inspection', tag: 'Professional Diploma',
    short: 'A foundation that prepares you for CSWIP and AWS.',
    overview: 'A foundation course in welding processes, defectology, inspection techniques, codes and standards and metallurgy. It also helps you prepare for certified welding courses such as CSWIP and AWS.',
    dur: '3 months', elig: 'Diploma / Degree', cert: STED,
    learn: ['Welding processes', 'Defectology', 'Inspection techniques', 'Codes and standards', 'Metallurgy', 'Preparation for CSWIP & AWS'],
    prompt: 'South Asian trainees in safety glasses watching a welder at work in a welding booth with bright sparks while an instructor explains, training workshop' },
  { slug: 'diploma-bim', cat: 'diploma', title: 'Building Information Modelling (BIM)', tag: 'Professional Diploma',
    short: 'A bundle of design and analysis software for the whole building lifecycle.',
    overview: 'A course bundle that trains you in different design and analysis software, helping you understand, evaluate and analyse processes in designing, constructing and managing buildings and structures.',
    dur: '6 months / 3 months', elig: 'Diploma / Degree', cert: STED,
    learn: ['BIM concepts and workflows', 'Architectural and MEP modelling', 'Structural modelling and analysis', 'Coordination and clash detection', 'Quantities and scheduling', 'Documentation'],
    prompt: 'a team of South Asian engineers around a large screen showing a colourful 3D BIM model of a building, hard hats and drawings on the meeting table' },
  { slug: 'diploma-logistics-scm', cat: 'diploma', title: 'Logistics & Supply Chain Management', tag: 'Professional Diploma',
    short: 'Logistics, inventory, foreign trade and shipping in one programme.',
    overview: 'A complete package covering logistics and supply chain concepts, inventory and stock control, foreign trade policy and the workings of shipping companies, warehouses and marine companies.',
    dur: '6 months', elig: 'Plus Two or above', cert: STED,
    learn: ['Logistics and supply chain concepts', 'Inventory and stock control', 'Warehousing', 'Foreign trade policy', 'Shipping and marine operations', 'Cost control across the supply chain'],
    prompt: 'a South Asian logistics manager with a tablet in a large modern warehouse with tall pallet racks and a forklift, bright organised aisles' },
  { slug: 'diploma-industrial-safety', cat: 'diploma', title: 'Industrial Safety Management', tag: 'Professional Diploma',
    short: 'A one-year programme in hazards, loss prevention and safety management – with IOSH.',
    overview: 'A full-time one-year programme giving the knowledge every industry needs to control fire accidents and manage foreseeable business losses: industrial hazards, loss-prevention techniques and procedures, and safety management. Includes free IOSH training and certification.',
    dur: 'One year', elig: 'Plus Two or above', cert: STED + ' · IOSH (free)',
    learn: ['Industrial hazards', 'Loss prevention techniques and procedures', 'Safety management systems', 'Fire and safety management', 'First aid', 'Free IOSH certification'],
    prompt: 'a South Asian safety officer in a white hard hat leading a toolbox talk with a group of workers in PPE at an industrial plant, early morning light' },
  { slug: 'diploma-fire-safety', cat: 'diploma', title: 'Fire & Safety Management', tag: 'Professional Diploma',
    short: 'Fire prevention, protection systems and emergency response.',
    overview: 'Prepares you for fire and safety roles in industry, construction and facilities: understanding how fires start and spread, the systems that protect people and assets, and how to plan and lead an emergency response.',
    dur: null, elig: null, cert: STED,
    learn: ['Fire science and fire prevention', 'Fire detection and protection systems', 'Firefighting equipment and techniques', 'Emergency response and evacuation', 'First aid', 'Safety audits and inspections'],
    prompt: 'a South Asian fire safety officer in turnout gear training a group of workers to use a fire extinguisher on a controlled fire at a training ground' },

  // ---------------- SHORT TERM ----------------
  { slug: 'fire-and-safety', cat: 'short', title: 'Fire & Safety', tag: 'Short Term',
    short: 'Essential fire prevention and firefighting skills.',
    overview: 'A focused course in fire prevention and basic firefighting, with theory and practical sessions.',
    dur: '20 days', elig: 'Plus Two or above', cert: STED,
    learn: ['Fire triangle and classes of fire', 'Fire extinguishers and their use', 'Hose and hydrant drills', 'Evacuation procedures', 'Basic first aid'],
    prompt: 'South Asian trainees in firefighting helmets and turnout coats handling a charged fire hose during a drill at a fire training ground, water spray' },
  { slug: 'industrial-safety', cat: 'short', title: 'Industrial Safety', tag: 'Short Term',
    short: 'Hazard recognition and safe work practices for industry.',
    overview: 'Covers the hazards found on industrial and construction sites and the controls that keep people safe, with theory and practical sessions.',
    dur: '20 days', elig: 'Diploma / Degree', cert: STED,
    learn: ['Hazard identification and risk assessment', 'Permit-to-work systems', 'Working at height and fall protection', 'Confined space entry', 'PPE selection and use', 'Incident reporting'],
    prompt: 'a South Asian safety trainer checking the fall-arrest harness of a young worker before work at height, steel structure and scaffolding behind' },
  { slug: 'welding-inspection', cat: 'short', title: 'Welding Inspection', tag: 'Short Term',
    short: 'A practical introduction to inspecting welds.',
    overview: 'A short, practical course on welding processes and the visual inspection of welds, for anyone starting out in fabrication and inspection.',
    dur: '20 days', elig: 'Plus Two or above', cert: STED,
    learn: ['Welding processes', 'Weld joints and symbols', 'Weld defects', 'Visual inspection with gauges', 'Inspection reporting'],
    prompt: 'close-up of a South Asian trainee inspecting a fresh weld bead on a steel test plate with a magnifying glass and a small torch, training workshop bokeh' },
  { slug: 'painting-inspection', cat: 'short', title: 'Painting Inspection', tag: 'Short Term',
    short: 'Surface preparation, coating application and inspection basics.',
    overview: 'A practical introduction to industrial painting inspection, from surface preparation to film thickness checks and reporting.',
    dur: '20 days', elig: 'Plus Two or above', cert: STED,
    learn: ['Surface preparation standards', 'Paint types and application', 'Environmental condition checks', 'Wet and dry film thickness', 'Coating defects'],
    prompt: 'a South Asian painting inspector checking the surface profile of freshly blast-cleaned steel with a surface comparator and gauge in a blasting shop' },
  { slug: 'solar-testing-commissioning', cat: 'short', title: 'Solar Testing & Commissioning', tag: 'Short Term',
    short: 'Test and commission solar PV systems safely.',
    overview: 'Learn how solar PV systems are put together and how to test and commission them safely so they perform as designed.',
    dur: null, elig: null, cert: STED,
    learn: ['Solar PV fundamentals', 'System components and layouts', 'Installation checks', 'Electrical testing of PV strings', 'Commissioning and documentation'],
    prompt: 'a South Asian technician in a hard hat testing a rooftop solar panel array with a multimeter and PV tester, rows of panels under a bright blue sky' },
  { slug: 'life-skills', cat: 'short', title: 'Life Skills', tag: 'Short Term',
    short: 'Personality, communication and interview skills for your career.',
    overview: 'Soft skills that help technical professionals succeed: presenting yourself well, managing time, communicating clearly and performing in interviews.',
    dur: null, elig: null, cert: STED,
    learn: ['Personality development', 'Time management', 'Communication skills', 'Interview skills'],
    prompt: 'a group of young South Asian professionals in a bright modern seminar room during a communication skills workshop, one presenting confidently while others listen and smile' }
];
